"""Aggiunta colonna yeast_ratio

Revision ID: 56e958a68bc7
Revises: 
Create Date: 2026-06-09 09:39:19.459085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e958a68bc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yeast_ratio', sa.Float(), server_default='3.0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('yeast_ratio')

    # ### end Alembic commands ###
